import { chmod, readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";

export interface IEnvConfig {
  domain: string;
  acmeEmail: string;
}

const hex = (bytes: number): string => randomBytes(bytes).toString("hex");

const renderEnv = (cfg: IEnvConfig): string => {
  const dbPassword = hex(24);
  const jwtSecret = hex(32);
  const jwtRefreshSecret = hex(32);
  const encryptionKey = hex(32);
  const webhookSecret = hex(32);

  return `# DeployKit configuration — generated by @deploykit/cli
    # Do not share this file.

    DOMAIN=${cfg.domain}
    ACME_EMAIL=${cfg.acmeEmail}

    # Database
    DB_USER=deploykit
    DB_PASSWORD=${dbPassword}
    DB_NAME=deploykit

    # Auth
    JWT_SECRET=${jwtSecret}
    JWT_REFRESH_SECRET=${jwtRefreshSecret}

    # Encryption (env vars stored in DB)
    ENCRYPTION_KEY=${encryptionKey}

    # Webhooks
    WEBHOOK_SECRET=${webhookSecret}
    `;
};

export const writeFreshEnv = async (
  path: string,
  cfg: IEnvConfig,
): Promise<void> => {
  await writeFile(path, renderEnv(cfg), "utf8");
  await chmod(path, 0o600);
};

export const updateEnvDomain = async (
  path: string,
  cfg: IEnvConfig,
): Promise<void> => {
  const raw = await readFile(path, "utf8");
  const next = raw
    .replace(/^DOMAIN=.*/m, `DOMAIN=${cfg.domain}`)
    .replace(/^ACME_EMAIL=.*/m, `ACME_EMAIL=${cfg.acmeEmail}`);
  await writeFile(path, next, "utf8");
};

export const envExists = (path: string): boolean => existsSync(path);
